name: CI
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -cover ./...
  build-container-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cashflow-api:latest
